### ISSUE TITLE
Whitelist User

### ISSUE THREAD

**Issue by 4nkitd** [lvkdotsh/edgeserver#65]
Q : How does one whitelist himself ?
`Note :  tried adding an entry to owners table with a random user_id and wallet address`
 
![image](https://user-images.githubusercontent.com/52023083/175821887-0300ef86-5317-4551-9f76-f3a0b0aae854.png)

Q : What is the relation of database tables ?

**Comment by svemat01** [comment]
There is now a setup screen for first-time setup, the first account to setup Edgeserver becomes admin and has UI access to whitelist new users.
